version: '3.3'

services:
  web:
    build: ./TestAlice
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./TestAlice:/usr/src/app/TestAlice/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - redis
  redis:
    image: redis:6.0.9-alpine
    
