# Generated by Django 3.1.3 on 2020-11-10 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('session_id', models.CharField(max_length=100)),
                ('request_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('command', models.TextField()),
            ],
        ),
    ]
